services:
  api:
    build:
      context: .
      dockerfile: src/L.TicTacToe.API/Dockerfile
    container_name: tictactoe.api
    environment:
      - GameOptions__TableSize:${TABLE_SIZE}
      - GameOptions__WinLength:${WIN_LENGTH}
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
  
  db:
    image: postgres:17.5-alpine3.22
    container_name: postgresql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  postgresql-data: